In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Input AutoStructure data

In [2]:
cols=[i for i in range(9)]
LEV=pd.read_csv("ic-ishftic/olg",sep='\s+',header='infer',skiprows=6410,nrows=162,usecols=cols)
LEV['2J']=LEV['2J']/2
LEV.rename(columns={"2J": "J"},inplace=True)

In [3]:
E1=pd.read_csv("ic-ishftic/olg",sep='\s+',header='infer',skiprows=6667,nrows=2589)

In [4]:
E2=pd.read_csv("ic-ishftic/olg",sep='\s+',header='infer',skiprows=9258,nrows=3892)

In [5]:
E3=pd.read_csv("ic-ishftic/olg",sep='\s+',header='infer',skiprows=12561,nrows=4792)

In [6]:
# 3s5g - CF=12
lev_3s5g=LEV.loc[LEV.loc[:]['CF']==12][:]
n3s5g=len(lev_3s5g)
lev_3s5g

     K  LV   T     K*CM  2*S+1  L    J  CF  (EK-E1)/RY
43  44  35  20  57259.0      1  4  4.0  12    0.521783
44  45  51  15  57259.0      3  4  3.0  12    0.521783
45  46  17  15  57259.0      3  4  5.0  12    0.521783
46  47  30  15  57259.0      3  4  4.0  12    0.521783

In [7]:
# 3s6h - CF=19
lev_3s6h=LEV.loc[LEV.loc[:]['CF']==19][:]
n3s6h=len(lev_3s6h)
lev_3s6h

     K  LV   T     K*CM  2*S+1  L    J  CF  (EK-E1)/RY
68  69  26  11  58615.0     -1  5  5.0  19    0.534142
69  70  40   7  58615.0     -3  5  4.0  19    0.534142
70  71  11   7  58615.0     -3  5  6.0  19    0.534142
71  72  22   7  58615.0     -3  5  5.0  19    0.534142

In [8]:
# 3s6g - CF=18
lev_3s6g=LEV.loc[LEV.loc[:]['CF']==18][:]
n3s6g=len(lev_3s6g)
lev_3s6g

     K  LV   T     K*CM  2*S+1  L    J  CF  (EK-E1)/RY
64  65  36  21  58607.0      1  4  4.0  18    0.534067
65  66  52  16  58607.0      3  4  3.0  18    0.534067
66  67  18  16  58607.0      3  4  5.0  18    0.534067
67  68  31  16  58607.0      3  4  4.0  18    0.534067

In [9]:
# 3s7h - CF=25
lev_3s7h=LEV.loc[LEV.loc[:]['CF']==25][:]
n3s7h=len(lev_3s7h)
lev_3s7h

     K  LV   T     K*CM  2*S+1  L    J  CF  (EK-E1)/RY
90  91  27  12  59425.0     -1  5  5.0  25    0.541522
91  92  41   8  59425.0     -3  5  4.0  25    0.541522
92  93  12   8  59425.0     -3  5  6.0  25    0.541522
93  94  23   8  59425.0     -3  5  5.0  25    0.541522

In [10]:
# 3s7i - CF=26
lev_3s7i=LEV.loc[LEV.loc[:]['CF']==26][:]
n3s7i=len(lev_3s7i)
lev_3s7i

     K  LV  T     K*CM  2*S+1  L    J  CF  (EK-E1)/RY
94  95   8  5  59427.0      1  6  6.0  26    0.541537
95  96  15  3  59427.0      3  6  5.0  26    0.541537
96  97   2  3  59427.0      3  6  7.0  26    0.541537
97  98   6  3  59427.0      3  6  6.0  26    0.541537

# Copy transition data of interest in new DataFrame

In [11]:
header=['K','LV','T','2*S+1','L','J','CF']
vformat=' '
hformat=' '
for i in range(7):
    vformat=vformat+'{v['+str(i)+']:.0f}\t ' 
    hformat=hformat+'{v['+str(i)+']}\t '

In [12]:
dat1=E1.loc[-1:-1][:]
for k in lev_3s5g['K']:
    for kp in lev_3s6h['K']:
        print(k,"==>",kp)
        lk=LEV.iloc[k-1][header].tolist()
        lkp=LEV.iloc[kp-1][header].tolist()
        print(hformat.format(v=header))
        print(vformat.format(v=lk))
        print(vformat.format(v=lkp))
        dummy=E1.loc[(E1.loc[:]['K']==kp) & (E1.loc[:]['KP']==k)]
        if dummy.empty==True:
            dummy=E2.loc[(E2.loc[:]['K']==kp) & (E2.loc[:]['KP']==k)]
            if dummy.empty==True:
                dummy=E3.loc[(E3.loc[:]['K']==kp) & (E3.loc[:]['KP']==k)]
                if dummy.empty==True:
                    print("not found")
                else:
                    print("type: E3")
                    dat1=dat1.append(dummy)
            else:
                print("type: E2")
                dat1=dat1.append(dummy)
        else:
            print("type: E1")
            dat1=dat1.append(dummy)
        print('=========')

for k in lev_3s6g['K']:
    for kp in lev_3s7h['K']:
        print(k,"==>",kp)
        lk=LEV.iloc[k-1][header].tolist()
        lkp=LEV.iloc[kp-1][header].tolist()
        print(hformat.format(v=header))
        print(vformat.format(v=lk))
        print(vformat.format(v=lkp))
        dummy=E1.loc[(E1.loc[:]['K']==kp) & (E1.loc[:]['KP']==k)]
        if dummy.empty==True:
            dummy=E2.loc[(E2.loc[:]['K']==kp) & (E2.loc[:]['KP']==k)]
            if dummy.empty==True:
                dummy=E3.loc[(E3.loc[:]['K']==kp) & (E3.loc[:]['KP']==k)]
                if dummy.empty==True:
                    print("not found")
                else:
                    print("type: E3")
                    dat1=dat1.append(dummy)
            else:
                print("type: E2")
                dat1=dat1.append(dummy)
        else:
            print("type: E1")
            dat1=dat1.append(dummy)
        print('=========')
        

for k in lev_3s6h['K']:
    for kp in lev_3s7i['K']:
        print(k,"==>",kp)
        lk=LEV.iloc[k-1][header].tolist()
        lkp=LEV.iloc[kp-1][header].tolist()
        print(hformat.format(v=header))
        print(vformat.format(v=lk))
        print(vformat.format(v=lkp))
        dummy=E1.loc[(E1.loc[:]['K']==kp) & (E1.loc[:]['KP']==k)]
        if dummy.empty==True:
            dummy=E2.loc[(E2.loc[:]['K']==kp) & (E2.loc[:]['KP']==k)]
            if dummy.empty==True:
                dummy=E3.loc[(E3.loc[:]['K']==kp) & (E3.loc[:]['KP']==k)]
                if dummy.empty==True:
                    print("not found")
                else:
                    print("type: E3")
                    dat1=dat1.append(dummy)
            else:
                print("type: E2")
                dat1=dat1.append(dummy)
        else:
            print("type: E1")
            dat1=dat1.append(dummy)
        print('=========')

44 ==> 69
 K	 LV	 T	 2*S+1	 L	 J	 CF
 44	 35	 20	 1	 4	 4	 12
 69	 26	 11	 -1	 5	 5	 19
type: E1
=========
44 ==> 70
 K	 LV	 T	 2*S+1	 L	 J	 CF
 44	 35	 20	 1	 4	 4	 12
 70	 40	 7	 -3	 5	 4	 19
type: E1
=========
44 ==> 71
 K	 LV	 T	 2*S+1	 L	 J	 CF
 44	 35	 20	 1	 4	 4	 12
 71	 11	 7	 -3	 5	 6	 19
not found
=========
44 ==> 72
 K	 LV	 T	 2*S+1	 L	 J	 CF
 44	 35	 20	 1	 4	 4	 12
 72	 22	 7	 -3	 5	 5	 19
type: E1
=========
45 ==> 69
 K	 LV	 T	 2*S+1	 L	 J	 CF
 45	 51	 15	 3	 4	 3	 12
 69	 26	 11	 -1	 5	 5	 19
not found
=========
45 ==> 70
 K	 LV	 T	 2*S+1	 L	 J	 CF
 45	 51	 15	 3	 4	 3	 12
 70	 40	 7	 -3	 5	 4	 19
type: E1
=========
45 ==> 71
 K	 LV	 T	 2*S+1	 L	 J	 CF
 45	 51	 15	 3	 4	 3	 12
 71	 11	 7	 -3	 5	 6	 19
not found
=========
45 ==> 72
 K	 LV	 T	 2*S+1	 L	 J	 CF
 45	 51	 15	 3	 4	 3	 12
 72	 22	 7	 -3	 5	 5	 19
not found
=========
46 ==> 69
 K	 LV	 T	 2*S+1	 L	 J	 CF
 46	 17	 15	 3	 4	 5	 12
 69	 26	 11	 -1	 5	 5	 19
type: E1
=========
46 ==> 70
 K	 LV	 T	 2*S+1	 L	 J	 CF
 46	 17	 15	 3	 4	 5	 12
 70	 40	 7	 -3	 5	 4	 19
type: E1
=========
46 ==> 71
 K	 LV	 T	 2*S+1	 L	 J	 CF
 46	 17	 15	 3	 4	 5	 12
 71	 11	 7	 -3	 5	 6	 19
type: E1
=========
46 ==> 72
 K	 LV	 T	 2*S+1	 L	 J	 CF
 46	 17	 15	 3	 4	 5	 12
 72	 22	 7	 -3	 5	 5	 19
type: E1
=========
47 ==> 69
 K	 LV	 T	 2*S+1	 L	 J	 CF
 47	 30	 15	 3	 4	 4	 12
 69	 26	 11	 -1	 5	 5	 19
type: E1
=========
47 ==> 70
 K	 LV	 T	 2*S+1	 L	 J	 CF
 47	 30	 15	 3	 4	 4	 12
 70	 40	 7	 -3	 5	 4	 19
type: E1
=========
47 ==> 71
 K	 LV	 T	 2*S+1	 L	 J	 CF
 47	 30	 15	 3	 4	 4	 12
 71	 11	 7	 -3	 5	 6	 19
not found
=========
47 ==> 72
 K	 LV	 T	 2*S+1	 L	 J	 CF
 47	 30	 15	 3	 4	 4	 12
 72	 22	 7	 -3	 5	 5	 19
type: E1
=========
65 ==> 91
 K	 LV	 T	 2*S+1	 L	 J	 CF
 65	 36	 21	 1	 4	 4	 18
 91	 27	 12	 -1	 5	 5	 25
type: E1
=========
65 ==> 92
 K	 LV	 T	 2*S+1	 L	 J	 CF
 65	 36	 21	 1	 4	 4	 18
 92	 41	 8	 -3	 5	 4	 25
type: E1
=========
65 ==> 93
 K	 LV	 T	 2*S+1	 L	 J	 CF
 65	 36	 21	 1	 4	 4	 18
 93	 12	 8	 -3	 5	 6	 25
not found
=========
65 ==> 94
 K	 LV	 T	 2*S+1	 L	 J	 CF
 65	 36	 21	 1	 4	 4	 18
 94	 23	 8	 -3	 5	 5	 25
type: E1
=========
66 ==> 91
 K	 LV	 T	 2*S+1	 L	 J	 CF
 66	 52	 16	 3	 4	 3	 18
 91	 27	 12	 -1	 5	 5	 25
not found
=========
66 ==> 92
 K	 LV	 T	 2*S+1	 L	 J	 CF
 66	 52	 16	 3	 4	 3	 18
 92	 41	 8	 -3	 5	 4	 25
type: E1
=========
66 ==> 93
 K	 LV	 T	 2*S+1	 L	 J	 CF
 66	 52	 16	 3	 4	 3	 18
 93	 12	 8	 -3	 5	 6	 25
not found
=========
66 ==> 94
 K	 LV	 T	 2*S+1	 L	 J	 CF
 66	 52	 16	 3	 4	 3	 18
 94	 23	 8	 -3	 5	 5	 25
not found
=========
67 ==> 91
 K	 LV	 T	 2*S+1	 L	 J	 CF
 67	 18	 16	 3	 4	 5	 18
 91	 27	 12	 -1	 5	 5	 25
type: E1
=========
67 ==> 92
 K	 LV	 T	 2*S+1	 L	 J	 CF
 67	 18	 16	 3	 4	 5	 18
 92	 41	 8	 -3	 5	 4	 25
type: E1
=========
67 ==> 93
 K	 LV	 T	 2*S+1	 L	 J	 CF
 67	 18	 16	 3	 4	 5	 18
 93	 12	 8	 -3	 5	 6	 25
type: E1
=========
67 ==> 94
 K	 LV	 T	 2*S+1	 L	 J	 CF
 67	 18	 16	 3	 4	 5	 18
 94	 23	 8	 -3	 5	 5	 25
type: E1
=========
68 ==> 91
 K	 LV	 T	 2*S+1	 L	 J	 CF
 68	 31	 16	 3	 4	 4	 18
 91	 27	 12	 -1	 5	 5	 25
type: E1
=========
68 ==> 92
 K	 LV	 T	 2*S+1	 L	 J	 CF
 68	 31	 16	 3	 4	 4	 18
 92	 41	 8	 -3	 5	 4	 25
type: E1
=========
68 ==> 93
 K	 LV	 T	 2*S+1	 L	 J	 CF
 68	 31	 16	 3	 4	 4	 18
 93	 12	 8	 -3	 5	 6	 25
not found
=========
68 ==> 94
 K	 LV	 T	 2*S+1	 L	 J	 CF
 68	 31	 16	 3	 4	 4	 18
 94	 23	 8	 -3	 5	 5	 25
type: E1
=========
69 ==> 95
 K	 LV	 T	 2*S+1	 L	 J	 CF
 69	 26	 11	 -1	 5	 5	 19
 95	 8	 5	 1	 6	 6	 26
type: E1
=========
69 ==> 96
 K	 LV	 T	 2*S+1	 L	 J	 CF
 69	 26	 11	 -1	 5	 5	 19
 96	 15	 3	 3	 6	 5	 26
type: E1
=========
69 ==> 97
 K	 LV	 T	 2*S+1	 L	 J	 CF
 69	 26	 11	 -1	 5	 5	 19
 97	 2	 3	 3	 6	 7	 26
not found
=========
69 ==> 98
 K	 LV	 T	 2*S+1	 L	 J	 CF
 69	 26	 11	 -1	 5	 5	 19
 98	 6	 3	 3	 6	 6	 26
type: E1
=========
70 ==> 95
 K	 LV	 T	 2*S+1	 L	 J	 CF
 70	 40	 7	 -3	 5	 4	 19
 95	 8	 5	 1	 6	 6	 26
not found
=========
70 ==> 96
 K	 LV	 T	 2*S+1	 L	 J	 CF
 70	 40	 7	 -3	 5	 4	 19
 96	 15	 3	 3	 6	 5	 26
type: E1
=========
70 ==> 97
 K	 LV	 T	 2*S+1	 L	 J	 CF
 70	 40	 7	 -3	 5	 4	 19
 97	 2	 3	 3	 6	 7	 26
not found
=========
70 ==> 98
 K	 LV	 T	 2*S+1	 L	 J	 CF
 70	 40	 7	 -3	 5	 4	 19
 98	 6	 3	 3	 6	 6	 26
not found
=========
71 ==> 95
 K	 LV	 T	 2*S+1	 L	 J	 CF
 71	 11	 7	 -3	 5	 6	 19
 95	 8	 5	 1	 6	 6	 26
type: E1
=========
71 ==> 96
 K	 LV	 T	 2*S+1	 L	 J	 CF
 71	 11	 7	 -3	 5	 6	 19
 96	 15	 3	 3	 6	 5	 26
type: E1
=========
71 ==> 97
 K	 LV	 T	 2*S+1	 L	 J	 CF
 71	 11	 7	 -3	 5	 6	 19
 97	 2	 3	 3	 6	 7	 26
type: E1
=========
71 ==> 98
 K	 LV	 T	 2*S+1	 L	 J	 CF
 71	 11	 7	 -3	 5	 6	 19
 98	 6	 3	 3	 6	 6	 26
type: E1
=========
72 ==> 95
 K	 LV	 T	 2*S+1	 L	 J	 CF
 72	 22	 7	 -3	 5	 5	 19
 95	 8	 5	 1	 6	 6	 26
type: E1
=========
72 ==> 96
 K	 LV	 T	 2*S+1	 L	 J	 CF
 72	 22	 7	 -3	 5	 5	 19
 96	 15	 3	 3	 6	 5	 26
type: E1
=========
72 ==> 97
 K	 LV	 T	 2*S+1	 L	 J	 CF
 72	 22	 7	 -3	 5	 5	 19
 97	 2	 3	 3	 6	 7	 26
not found
=========
72 ==> 98
 K	 LV	 T	 2*S+1	 L	 J	 CF
 72	 22	 7	 -3	 5	 5	 19
 98	 6	 3	 3	 6	 6	 26
type: E1
=========

In [13]:
dat1

,E1-DATA,K,KP,A(EK)*SEC,S,G*F,F(ABS),-F(EMI),WAVEL/AE,GF(VEL),ALPHA(POL)
602,603,69,44,-1636000.0,**********,-14.660000,-1.62943,-1.33317,73736.3429,14.30000,42670.00
608,609,70,44,41220.0,73.396473,0.302400,0.03360,0.03360,73736.2917,-0.29600,879.80
618,619,72,44,-31970.0,-69.577985,-0.286600,-0.03185,-0.02606,73736.2405,0.28100,834.10
609,610,70,45,-1617000.0,**********,-11.860000,-1.69451,-1.31795,73736.4180,11.60000,44380.00
603,604,69,46,23730.0,51.656824,0.212800,0.01935,0.01935,73736.4692,-0.20800,506.70
610,611,70,46,-839.9,-1.495787,-0.006162,-0.00056,-0.00068,73736.4180,0.00603,14.67
616,617,71,46,-1701000.0,**********,-18.020000,-1.63850,-1.38642,73736.4180,17.60000,42910.00
619,620,72,46,44300.0,96.426118,0.397200,0.03611,0.03611,73736.3668,-0.38900,945.80
604,605,69,47,42060.0,91.542072,0.377100,0.04190,0.03428,73736.5956,-0.36800,1097.00
611,612,70,47,41940.0,74.686469,0.307700,0.03419,0.03419,73736.5443,-0.30100,895.30
620,621,72,47,-1625000.0,**********,-14.570000,-1.61877,-1.32445,73736.4931,14.30000,42400.00
976,977,91,65,-537400.0,**********,-13.240000,-1.47138,-1.20386,122240.6127,12.90000,105900.00
986,987,92,65,13400.0,108.713397,0.270100,0.03002,0.03002,122240.5269,-0.26400,2160.00
1000,1001,94,65,-2771.0,-27.484027,-0.068300,-0.00759,-0.00621,122240.4412,0.06710,546.20
987,988,92,66,-523600.0,**********,-10.560000,-1.50825,-1.17308,122240.7278,10.30000,108600.00
977,978,91,67,9162.0,90.853598,0.225800,0.02052,0.02052,122240.8135,-0.22100,1477.00
988,989,92,67,-272.0,-2.207146,-0.005485,-0.00050,-0.00061,122240.7278,0.00536,35.89
995,996,93,67,-550800.0,**********,-16.040000,-1.45839,-1.23402,122240.7278,15.70000,105000.00
1001,1002,94,67,12870.0,127.653897,0.317200,0.02884,0.02884,122240.6421,-0.31000,2076.00
978,979,91,68,4616.0,45.778744,0.113800,0.01264,0.01034,122241.0144,-0.11100,909.80
989,990,92,68,13530.0,109.794098,0.272800,0.03031,0.03031,122240.9287,-0.26700,2182.00
1002,1003,94,68,-535400.0,**********,-13.190000,-1.46602,-1.19947,122240.8430,12.90000,105500.00
1006,1007,95,69,-710000.0,**********,-21.010000,-1.90989,-1.61606,123217.1569,20.90000,139700.00
1012,1013,96,69,8578.0,87.120629,0.214800,0.01952,0.01952,123217.0739,-0.21300,1428.00
1022,1023,98,69,-31790.0,**********,-0.940800,-0.08553,-0.07237,123216.9909,0.93400,6255.00
1013,1014,96,70,-724300.0,**********,-18.130000,-2.01494,-1.64858,123217.2169,18.00000,147400.00
1007,1008,95,71,3407.0,40.893208,0.100800,0.00775,0.00775,123217.2999,-0.10000,567.10
1014,1015,96,71,-172.0,-1.746475,-0.004305,-0.00033,-0.00039,123217.2169,0.00428,24.22
1020,1021,97,71,-749000.0,**********,-25.570000,-1.96724,-1.70495,123217.2169,25.40000,143900.00
1023,1024,98,71,17400.0,208.852674,0.514900,0.03961,0.03961,123217.1340,-0.51100,2896.00
1008,1009,95,72,35650.0,427.869775,1.055000,0.09589,0.08114,123217.4429,-1.05000,7013.00
1015,1016,96,72,16010.0,162.625253,0.400900,0.03645,0.03645,123217.3600,-0.39800,2665.00
1024,1025,98,72,-699900.0,**********,-20.710000,-1.88260,-1.59297,123217.2770,20.60000,137700.00

# Operate over new dataframe with data of interest

In [14]:
# remove useless columns:
dat1.drop(columns=['E1-DATA','S', 'ALPHA(POL)'],inplace=True)
# take absolute value of gf and add its logarithm as new column
dat1['G*F']=abs(dat1['G*F'])
dat1['A(EK)*SEC']=abs(dat1['A(EK)*SEC'])
dat1['log(GF)']=np.log(dat1['G*F'])
# compute the relative error of GF in length and velocity gauge in new column:
dat1['ER% G*F']=(abs(dat1.loc[:]['G*F'])-abs(dat1.loc[:]['GF(VEL)']))/abs(dat1.loc[:]['G*F'])*100

# Input of database transition data to be updated

In [15]:
database=pd.read_csv("LineFine-um.dat",sep='\t',header='infer')
ndb=len(database)

In [16]:
database

,AtomicNumber,IonCharge,ModelIndex,LineNumber,type,LowerLevel,LowerSublevel,UpperLevel,UpperSublevel,Wavelength,...,EWavenLower,EWavenUpper,gLower,gUpper,2Jlower,2JUpper,broad,prd,nlteparm,commentid
0,12,0,1,670,1,26,2,39,1,73736.417,...,57262.760,58618.942,9,9,8,8,0,0,1,0
1,12,0,1,671,1,26,3,39,1,73736.417,...,57262.760,58618.942,11,9,10,8,0,0,1,0
2,12,0,1,672,1,27,1,39,2,73736.417,...,57262.760,58618.942,9,11,8,10,0,0,1,0
3,12,0,1,673,1,26,1,39,1,73736.417,...,57262.760,58618.942,7,9,6,8,0,0,1,0
4,12,0,1,674,1,27,1,40,1,73736.417,...,57262.760,58618.942,9,11,8,10,0,0,1,0
5,12,0,1,675,1,26,3,39,2,73736.417,...,57262.760,58618.942,11,11,10,10,0,0,1,0
6,12,0,1,676,1,26,3,40,1,73736.417,...,57262.760,58618.942,11,11,10,10,0,0,1,0
7,12,0,1,677,1,26,2,39,2,73736.417,...,57262.760,58618.942,9,11,8,10,0,0,1,0
8,12,0,1,678,1,27,1,39,1,73736.417,...,57262.760,58618.942,9,9,8,8,0,0,1,0
9,12,0,1,679,1,26,2,40,1,73736.417,...,57262.760,58618.942,9,11,8,10,0,0,1,0
10,12,0,1,680,1,26,3,39,3,73736.417,...,57262.760,58618.942,11,13,10,12,0,0,1,0
11,12,0,1,681,1,38,1,51,1,122240.720,...,58610.795,59428.853,9,9,8,8,0,0,1,0
12,12,0,1,682,1,37,1,51,3,122240.720,...,58610.795,59428.853,11,13,10,12,0,0,1,0
13,12,0,1,683,1,37,2,51,2,122240.720,...,58610.795,59428.853,9,11,8,10,0,0,1,0
14,12,0,1,684,1,37,2,52,1,122240.720,...,58610.795,59428.853,9,11,8,10,0,0,1,0
15,12,0,1,685,1,37,1,52,1,122240.720,...,58610.795,59428.853,11,11,10,10,0,0,1,0
16,12,0,1,686,1,37,1,51,2,122240.720,...,58610.795,59428.853,11,11,10,10,0,0,1,0
17,12,0,1,687,1,38,1,52,1,122240.720,...,58610.795,59428.853,9,11,8,10,0,0,1,0
18,12,0,1,688,1,38,1,51,2,122240.720,...,58610.795,59428.853,9,11,8,10,0,0,1,0
19,12,0,1,689,1,37,2,51,1,122240.720,...,58610.795,59428.853,9,9,8,8,0,0,1,0
20,12,0,1,690,1,37,1,51,1,122240.720,...,58610.795,59428.853,11,9,10,8,0,0,1,0
21,12,0,1,691,1,37,3,51,1,122240.720,...,58610.795,59428.853,7,9,6,8,0,0,1,0
22,12,0,1,692,1,40,1,53,2,123217.200,...,58618.942,59430.517,11,13,10,12,0,0,1,0
23,12,0,1,693,1,39,3,53,2,123217.200,...,58618.942,59430.517,13,13,12,12,0,0,1,0
24,12,0,1,694,1,39,3,53,1,123217.200,...,58618.942,59430.517,13,11,12,10,0,0,1,0
25,12,0,1,695,1,40,1,54,1,123217.200,...,58618.942,59430.517,11,13,10,12,0,0,1,0
26,12,0,1,696,1,39,2,53,1,123217.200,...,58618.942,59430.517,11,11,10,10,0,0,1,0
27,12,0,1,697,1,40,1,53,1,123217.200,...,58618.942,59430.517,11,11,10,10,0,0,1,0
28,12,0,1,698,1,39,3,53,3,123217.200,...,58618.942,59430.517,13,15,12,14,0,0,1,0
29,12,0,1,699,1,39,2,54,1,123217.200,...,58618.942,59430.517,11,13,10,12,0,0,1,0
30,12,0,1,700,1,39,3,54,1,123217.200,...,58618.942,59430.517,13,13,12,12,0,0,1,0
31,12,0,1,701,1,39,1,53,1,123217.200,...,58618.942,59430.517,9,11,8,10,0,0,1,0
32,12,0,1,702,1,39,2,53,2,123217.200,...,58618.942,59430.517,11,13,10,12,0,0,1,0

In [17]:
# en DataBase:    en AS:
#
# 3s5g-3G:
#  LwLev=26       T=15
#   LwSub=1        K=45   --  J=3
#   LwSub=2        K=47   --  J=4
#   LwSub=3        K=46   --  J=5
#
# 3s5g-1G:
#  LwLv=27        T=20
#   LwSub=1        K=44   --  J=4 
#
# ---------------------------------
#
# 3s6h-3H:
#  LwLv=39        T=7
#   LwSub=1        K=70   --  J=4
#   LwSub=2        K=72   --  J=5
#   LwSub=3        K=71   --  J=6
#
# 3s6h-1H:
#  LwLv=40        T=11
#   LwSub=1        K=69   --  J=5
#
# 3s6g-3G:
#  LwLev=37       T=16
#   LwSub=1        K=67   --  J=5
#   LwSub=2        K=68   --  J=4
#   LwSub=3        K=66   --  J=3
#
# 3s6g-1G:
#  LwLv=38        T=21
#   LwSub=1        K=65   --  J=4
#
# ---------------------------------
#
# 3s7h-3H:
#  LwLv=51        T=8
#   LwSub=1        K=92   --  J=4
#   LwSub=2        K=94   --  J=5
#   LwSub=3        K=93   --  J=6
#
# 3s7h-1H:
#  LwLv=52        T=12
#   LwSub=1        K=91   --  J=5
#       
# 3s7i-3I:
#  LwLv=53        T=3
#   LwSub=1        K=96   --  J=5
#   LwSub=2        K=98   --  J=6
#   LwSub=3        K=97   --  J=7
#
# 3s7i-1I:
#  LwLv=54        T=5
#   LwSub=1       K=95 --  J=6
#

In [18]:
as2db={44:[27,1],                     # 3s5g-1G
       45:[26,1],46:[26,3],47:[26,2], # 3s5g-3G
       69:[40,1],                     # 3s6h-1H
       70:[39,1],71:[39,3],72:[39,2], # 3s6h-3H
       65:[38,1],                     # 3s6g-1G
       66:[37,3],67:[37,1],68:[37,2], # 3s6g-3G
       91:[52,1],                     # 3s7h-1H
       92:[51,1],93:[51,3],94:[51,2], # 3s7h-3H
       95:[54,1],                     # 3s7i-1I
       96:[53,1],97:[53,3],98:[53,2], # 3s7i-3I
       }

In [27]:
database.iloc[:]['Wavelength']

0      73736.417
1      73736.417
2      73736.417
3      73736.417
4      73736.417
5      73736.417
6      73736.417
7      73736.417
8      73736.417
9      73736.417
10     73736.417
11    122240.720
12    122240.720
13    122240.720
14    122240.720
15    122240.720
16    122240.720
17    122240.720
18    122240.720
19    122240.720
20    122240.720
21    122240.720
22    123217.200
23    123217.200
24    123217.200
25    123217.200
26    123217.200
27    123217.200
28    123217.200
29    123217.200
30    123217.200
31    123217.200
32    123217.200
Name: Wavelength, dtype: float64

In [32]:
database_updated=database.copy()
print('        database     AS')
for i in range(ndb):
    print(i)
    dumm=database.iloc[i:i+1][:]
    lwlv=dumm.iloc[0]['LowerLevel']
    lwsub=dumm.iloc[0]['LowerSublevel']
    uplv=dumm.iloc[0]['UpperLevel']
    upsub=dumm.iloc[0]['UpperSublevel']
    for (auto, dbase) in as2db.items():
        if (lwlv==dbase[0]) & (lwsub==dbase[1]):
            lw_as=auto
            print('lower=  ',int(lwlv),",",int(lwsub)," == ",auto)
        if (uplv==dbase[0]) & (upsub==dbase[1]):
            up_as=auto
            print('upper=  ',int(uplv),",",int(upsub)," == ",auto)
    dum2=dat1.loc[:][(dat1.loc[:]['K']==up_as)&(dat1.loc[:]['KP']==lw_as)]
    print(dum2)
    as_gf=dum2.loc[:]['G*F'].tolist()
    as_A=dum2.loc[:]['A(EK)*SEC'].tolist()
    as_wavelength=dum2.loc[:]['WAVEL/AE'].tolist()
    print(as_gf,as_A,as_wavelength)
    database_updated.at[i,'gf']=as_gf[0]
    database_updated.at[i,'A']=as_A[0]
#     database_updated.at[i,'Wavelength']=as_wavelength[0]
    print(' ')

        database     AS
0
lower=   26 , 2  ==  47
upper=   39 , 1  ==  70
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
611  70  47    41940.0  0.3077  0.03419  0.03419  73736.5443   -0.301

     log(GF)   ER% G*F
611 -1.17863  2.177446
[0.3077] [41940.0] ['73736.5443']

1
lower=   26 , 3  ==  46
upper=   39 , 1  ==  70
      K  KP  A(EK)*SEC       G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
610  70  46      839.9  0.006162 -0.00056 -0.00068  73736.4180  0.00603

      log(GF)   ER% G*F
610 -5.089354  2.142162
[0.006162] [839.9] ['73736.4180']

2
lower=   27 , 1  ==  44
upper=   39 , 2  ==  72
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
618  72  44    31970.0  0.2866 -0.03185 -0.02606  73736.2405    0.281

      log(GF)   ER% G*F
618 -1.249668  1.953943
[0.2866] [31970.0] ['73736.2405']

3
lower=   26 , 1  ==  45
upper=   39 , 1  ==  70
      K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
609  70  45  1617000.0  11.86 -1.69451 -1.31795  73736.4180     11.6

      log(GF)   ER% G*F
609  2.473171  2.192243
[11.86] [1617000.0] ['73736.4180']

4
lower=   27 , 1  ==  44
upper=   40 , 1  ==  69
      K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
602  69  44  1636000.0  14.66 -1.62943 -1.33317  73736.3429     14.3

      log(GF)   ER% G*F
602  2.685123  2.455662
[14.66] [1636000.0] ['73736.3429']

5
lower=   26 , 3  ==  46
upper=   39 , 2  ==  72
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
619  72  46    44300.0  0.3972  0.03611  0.03611  73736.3668   -0.389

      log(GF)   ER% G*F
619 -0.923315  2.064451
[0.3972] [44300.0] ['73736.3668']

6
lower=   26 , 3  ==  46
upper=   40 , 1  ==  69
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
603  69  46    23730.0  0.2128  0.01935  0.01935  73736.4692   -0.208

      log(GF)   ER% G*F
603 -1.547403  2.255639
[0.2128] [23730.0] ['73736.4692']

7
lower=   26 , 2  ==  47
upper=   39 , 2  ==  72
      K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
620  72  47  1625000.0  14.57 -1.61877 -1.32445  73736.4931     14.3

      log(GF)   ER% G*F
620  2.678965  1.853123
[14.57] [1625000.0] ['73736.4931']

8
lower=   27 , 1  ==  44
upper=   39 , 1  ==  70
      K  KP  A(EK)*SEC     G*F  F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
608  70  44    41220.0  0.3024  0.0336   0.0336  73736.2917   -0.296

      log(GF)   ER% G*F
608 -1.196005  2.116402
[0.3024] [41220.0] ['73736.2917']

9
lower=   26 , 2  ==  47
upper=   40 , 1  ==  69
      K  KP  A(EK)*SEC     G*F  F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)  \
604  69  47    42060.0  0.3771  0.0419  0.03428  73736.5956   -0.368

      log(GF)   ER% G*F
604 -0.975245  2.413153
[0.3771] [42060.0] ['73736.5956']

10
lower=   26 , 3  ==  46
upper=   39 , 3  ==  71
      K  KP  A(EK)*SEC    G*F  F(ABS)  -F(EMI)    WAVEL/AE  GF(VEL)   log(GF)  \
616  71  46  1701000.0  18.02 -1.6385 -1.38642  73736.4180     17.6  2.891482

      ER% G*F
616  2.330744
[18.02] [1701000.0] ['73736.4180']

11
lower=   38 , 1  ==  65
upper=   51 , 1  ==  92
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
986  92  65    13400.0  0.2701  0.03002  0.03002  122240.5269   -0.264

      log(GF)   ER% G*F
986 -1.308963  2.258423
[0.2701] [13400.0] ['122240.5269']

12
lower=   37 , 1  ==  67
upper=   51 , 3  ==  93
      K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
995  93  67   550800.0  16.04 -1.45839 -1.23402  122240.7278     15.7

      log(GF)   ER% G*F
995  2.775086  2.119701
[16.04] [550800.0] ['122240.7278']

13
lower=   37 , 2  ==  68
upper=   51 , 2  ==  94
       K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1002  94  68   535400.0  13.19 -1.46602 -1.19947  122240.8430     12.9

       log(GF)   ER% G*F
1002  2.579459  2.198635
[13.19] [535400.0] ['122240.8430']

14
lower=   37 , 2  ==  68
upper=   52 , 1  ==  91
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
978  91  68     4616.0  0.1138  0.01264  0.01034  122241.0144   -0.111

      log(GF)   ER% G*F
978 -2.173313  2.460457
[0.1138] [4616.0] ['122241.0144']

15
lower=   37 , 1  ==  67
upper=   52 , 1  ==  91
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
977  91  67     9162.0  0.2258  0.02052  0.02052  122240.8135   -0.221

      log(GF)   ER% G*F
977 -1.488106  2.125775
[0.2258] [9162.0] ['122240.8135']

16
lower=   37 , 1  ==  67
upper=   51 , 2  ==  94
       K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1001  94  67    12870.0  0.3172  0.02884  0.02884  122240.6421    -0.31

       log(GF)   ER% G*F
1001 -1.148223  2.269861
[0.3172] [12870.0] ['122240.6421']

17
lower=   38 , 1  ==  65
upper=   52 , 1  ==  91
      K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
976  91  65   537400.0  13.24 -1.47138 -1.20386  122240.6127     12.9

      log(GF)   ER% G*F
976  2.583243  2.567976
[13.24] [537400.0] ['122240.6127']

18
lower=   38 , 1  ==  65
upper=   51 , 2  ==  94
       K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1000  94  65     2771.0  0.0683 -0.00759 -0.00621  122240.4412   0.0671

       log(GF)   ER% G*F
1000 -2.683846  1.756955
[0.0683] [2771.0] ['122240.4412']

19
lower=   37 , 2  ==  68
upper=   51 , 1  ==  92
      K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
989  92  68    13530.0  0.2728  0.03031  0.03031  122240.9287   -0.267

      log(GF)  ER% G*F
989 -1.299016   2.1261
[0.2728] [13530.0] ['122240.9287']

20
lower=   37 , 1  ==  67
upper=   51 , 1  ==  92
      K  KP  A(EK)*SEC       G*F  F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
988  92  67      272.0  0.005485 -0.0005 -0.00061  122240.7278  0.00536

      log(GF)   ER% G*F
988 -5.205738  2.278943
[0.005485] [272.0] ['122240.7278']

21
lower=   37 , 3  ==  66
upper=   51 , 1  ==  92
      K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
987  92  66   523600.0  10.56 -1.50825 -1.17308  122240.7278     10.3

      log(GF)   ER% G*F
987  2.357073  2.462121
[10.56] [523600.0] ['122240.7278']

22
lower=   40 , 1  ==  69
upper=   53 , 2  ==  98
       K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1022  98  69    31790.0  0.9408 -0.08553 -0.07237  123216.9909    0.934

       log(GF)   ER% G*F
1022 -0.061025  0.722789
[0.9408] [31790.0] ['123216.9909']

23
lower=   39 , 3  ==  71
upper=   53 , 2  ==  98
       K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1023  98  71    17400.0  0.5149  0.03961  0.03961  123217.1340   -0.511

       log(GF)   ER% G*F
1023 -0.663783  0.757429
[0.5149] [17400.0] ['123217.1340']

24
lower=   39 , 3  ==  71
upper=   53 , 1  ==  96
       K  KP  A(EK)*SEC       G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1014  96  71      172.0  0.004305 -0.00033 -0.00039  123217.2169  0.00428

       log(GF)  ER% G*F
1014 -5.447978  0.58072
[0.004305] [172.0] ['123217.2169']

25
lower=   40 , 1  ==  69
upper=   54 , 1  ==  95
       K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1006  95  69   710000.0  21.01 -1.90989 -1.61606  123217.1569     20.9

       log(GF)  ER% G*F
1006  3.044999  0.52356
[21.01] [710000.0] ['123217.1569']

26
lower=   39 , 2  ==  72
upper=   53 , 1  ==  96
       K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1015  96  72    16010.0  0.4009  0.03645  0.03645  123217.3600   -0.398

       log(GF)   ER% G*F
1015 -0.914043  0.723372
[0.4009] [16010.0] ['123217.3600']

27
lower=   40 , 1  ==  69
upper=   53 , 1  ==  96
       K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1012  96  69     8578.0  0.2148  0.01952  0.01952  123217.0739   -0.213

       log(GF)   ER% G*F
1012 -1.538048  0.837989
[0.2148] [8578.0] ['123217.0739']

28
lower=   39 , 3  ==  71
upper=   53 , 3  ==  97
       K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1020  97  71   749000.0  25.57 -1.96724 -1.70495  123217.2169     25.4

      log(GF)   ER% G*F
1020  3.24142  0.664842
[25.57] [749000.0] ['123217.2169']

29
lower=   39 , 2  ==  72
upper=   54 , 1  ==  95
       K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1008  95  72    35650.0  1.055  0.09589  0.08114  123217.4429    -1.05

       log(GF)   ER% G*F
1008  0.053541  0.473934
[1.055] [35650.0] ['123217.4429']

30
lower=   39 , 3  ==  71
upper=   54 , 1  ==  95
       K  KP  A(EK)*SEC     G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1007  95  71     3407.0  0.1008  0.00775  0.00775  123217.2999     -0.1

       log(GF)   ER% G*F
1007 -2.294617  0.793651
[0.1008] [3407.0] ['123217.2999']

31
lower=   39 , 1  ==  70
upper=   53 , 1  ==  96
       K  KP  A(EK)*SEC    G*F   F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1013  96  70   724300.0  18.13 -2.01494 -1.64858  123217.2169     18.0

       log(GF)   ER% G*F
1013  2.897568  0.717044
[18.13] [724300.0] ['123217.2169']

32
lower=   39 , 2  ==  72
upper=   53 , 2  ==  98
       K  KP  A(EK)*SEC    G*F  F(ABS)  -F(EMI)     WAVEL/AE  GF(VEL)  \
1024  98  72   699900.0  20.71 -1.8826 -1.59297  123217.2770     20.6

       log(GF)   ER% G*F
1024  3.030617  0.531144
[20.71] [699900.0] ['123217.2770']

In [33]:
database_updated.to_csv(r'LineFine-updated.dat', header=True, index=None, sep='\t', mode='a')